---
mgmt_gateway: 10.0.0.1
mgmt_interface: Management1

custom_structured_configuration_ip_name_servers:
  - ip_address: 8.8.8.8
    vrf: MGMT

custom_structured_configuration_dns_domain: avd.lab

custom_structured_configuration_daemon_terminattr:
  cvaddrs:
    - apiserver.cv-prod-euwest-2.arista.io:443
  cvauth:
    method: token-secure
    token_file: /mnt/flash/cv-onboarding-token
  cvvrf: MGMT
  disable_aaa: true
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent

management_eapi:
  enable_http: false
  enable_https: true

# NTP servers
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: time.google.com
    - name: time.windows.com
    - name: time.apple.com

local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "$6$GgJDMeBVxpUHjqLw$LUbUYX7pnVUjvcxoaAeGW0llEhfuX9XKiQRRx7oqFTuHUEYeFxQmDwhT.XcQvAiJsOG7YtAoTGuV7nRTBxF6r1"

ansible_user: arista
ansible_password: arista
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)

