---
servers:

- name: marpla-h01
  adapters:
  - mode: trunk
    switch_ports:
    - Ethernet10
    - Ethernet10
    switches:
    - marpla-l01
    - marpla-l02
    vlans: 100
    port_channel:
      mode: active

- name: marpla-h02
  adapters:
  - mode: trunk
    switch_ports:
    - Ethernet20
    - Ethernet20
    switches:
    - marpla-l03
    - marpla-l04
    vlans: 200
    port_channel:
      mode: active
